In [34]:
import numpy as np
from keras.datasets import mnist
import keras
from keras import layers
from sklearn.metrics import classification_report, confusion_matrix

In [35]:
training_set, test_set = mnist.load_data()
X_train, y_train = training_set
X_test, y_test = test_set
print(X_train.shape)

(60000, 28, 28)


In [36]:
X_train = np.expand_dims(X_train, -1)
X_test = np.expand_dims(X_test, -1)
print(X_train.shape)

(60000, 28, 28, 1)


In [37]:
X_train = X_train.astype(np.float) / 255.0  
X_test = X_test.astype(np.float) / 255.0

C:\Users\nikos\AppData\Local\Temp\ipykernel_35324\1404525770.py:1: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_train = X_train.astype(np.float) / 255.0
C:\Users\nikos\AppData\Local\Temp\ipykernel_35324\1404525770.py:2: DeprecationWarning: `np.float` is a deprecated alias for the builtin `float`. To silence this warning, use `float` by itself. Doing this will not modify any behavior and is safe. If you specifically wanted the numpy scalar type, use `np.float64` here.
Deprecated in NumPy 1.20; for more details and guidance: https://numpy.org/devdocs/release/1.20.0-notes.html#deprecations
  X_test = X_test.astype(np.float) / 255.0


In [38]:
num_classes = 10
input_shape = (28, 28, 1)
batch_size = 128
epochs = 30

##### 1 layer linear NN

In [39]:
model1 = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [40]:
model1.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 flatten_4 (Flatten)         (None, 784)               0         
                                                                 
 dense_6 (Dense)             (None, 10)                7850      
                                                                 
Total params: 7,850
Trainable params: 7,850
Non-trainable params: 0
_________________________________________________________________


In [41]:
model1.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [42]:
model1.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 1ms/step - loss: 0.7475 - accuracy: 0.8195 - val_loss: 0.4096 - val_accuracy: 0.8999
Epoch 2/30
375/375 [==============================] - 0s 914us/step - loss: 0.3894 - accuracy: 0.8965 - val_loss: 0.3352 - val_accuracy: 0.9091
Epoch 3/30
375/375 [==============================] - 0s 912us/step - loss: 0.3386 - accuracy: 0.9078 - val_loss: 0.3076 - val_accuracy: 0.9150
Epoch 4/30
375/375 [==============================] - 0s 888us/step - loss: 0.3148 - accuracy: 0.9129 - val_loss: 0.2945 - val_accuracy: 0.9186
Epoch 5/30
375/375 [==============================] - 0s 904us/step - loss: 0.3009 - accuracy: 0.9166 - val_loss: 0.2855 - val_accuracy: 0.9205
Epoch 6/30
375/375 [==============================] - 0s 906us/step - loss: 0.2911 - accuracy: 0.9182 - val_loss: 0.2789 - val_accuracy: 0.9234
Epoch 7/30
375/375 [==============================] - 0s 904us/step - loss: 0.2841 - accuracy: 0.9205 - val_loss: 0.2743 - val_accuracy: 0

In [43]:
from sklearn.metrics import classification_report, confusion_matrix

y_probab = model1.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 410us/step
              precision    recall  f1-score   support

           0       0.95      0.98      0.97       980
           1       0.97      0.98      0.97      1135
           2       0.94      0.89      0.91      1032
           3       0.89      0.92      0.91      1010
           4       0.94      0.93      0.94       982
           5       0.91      0.87      0.89       892
           6       0.94      0.95      0.95       958
           7       0.93      0.93      0.93      1028
           8       0.88      0.90      0.89       974
           9       0.92      0.91      0.92      1009

    accuracy                           0.93     10000
   macro avg       0.93      0.93      0.93     10000
weighted avg       0.93      0.93      0.93     10000

[[ 963    0    1    2    0    6    5    2    1    0]
 [   0 1113    3    3    0    1    3    2   10    0]
 [   7   10  917   23    7    4   13    8   40    3]
 [   3    0   13  931    

#### 2 hidden non linear

In [44]:
model = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            keras.layers.Flatten(),
            layers.Dense(64, activation="tanh"),
            layers.Dense(128, activation="tanh"),
            layers.Dense(num_classes, activation="softmax")
        ]
    )

In [45]:
model.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])

In [46]:
model.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 1s 2ms/step - loss: 0.4004 - accuracy: 0.8876 - val_loss: 0.2136 - val_accuracy: 0.9387
Epoch 2/30
375/375 [==============================] - 1s 2ms/step - loss: 0.1894 - accuracy: 0.9441 - val_loss: 0.1605 - val_accuracy: 0.9537
Epoch 3/30
375/375 [==============================] - 1s 2ms/step - loss: 0.1373 - accuracy: 0.9595 - val_loss: 0.1401 - val_accuracy: 0.9586
Epoch 4/30
375/375 [==============================] - 1s 2ms/step - loss: 0.1073 - accuracy: 0.9684 - val_loss: 0.1172 - val_accuracy: 0.9638
Epoch 5/30
375/375 [==============================] - 1s 2ms/step - loss: 0.0849 - accuracy: 0.9752 - val_loss: 0.1097 - val_accuracy: 0.9672
Epoch 6/30
375/375 [==============================] - 1s 2ms/step - loss: 0.0690 - accuracy: 0.9795 - val_loss: 0.1051 - val_accuracy: 0.9686
Epoch 7/30
375/375 [==============================] - 1s 2ms/step - loss: 0.0589 - accuracy: 0.9825 - val_loss: 0.1023 - val_accuracy: 0.9708
Epoch 

##### evaluation

In [47]:
from sklearn.metrics import classification_report, confusion_matrix

y_probab = model.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 0s 558us/step
              precision    recall  f1-score   support

           0       0.97      0.99      0.98       980
           1       1.00      0.98      0.99      1135
           2       0.96      0.98      0.97      1032
           3       0.95      0.98      0.96      1010
           4       0.98      0.98      0.98       982
           5       0.98      0.96      0.97       892
           6       0.99      0.97      0.98       958
           7       0.98      0.97      0.97      1028
           8       0.97      0.97      0.97       974
           9       0.97      0.96      0.97      1009

    accuracy                           0.97     10000
   macro avg       0.97      0.97      0.97     10000
weighted avg       0.97      0.97      0.97     10000

[[ 972    0    1    2    0    1    1    1    2    0]
 [   2 1114    4    4    0    1    2    2    6    0]
 [   1    0 1011    5    4    0    2    5    4    0]
 [   0    0    9  988    

#### CNN

In [49]:
modelCNN = keras.Sequential(
        [
            keras.Input(shape=input_shape),
            layers.Conv2D(32, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Conv2D(64, kernel_size=(3, 3), activation="relu"),
            layers.MaxPooling2D(pool_size=(2, 2)),
            layers.Flatten(),
            layers.Dropout(0.5),
            layers.Dense(num_classes, activation="softmax"),
        ]
    )

In [50]:
modelCNN.compile(loss="sparse_categorical_crossentropy", optimizer="adam", metrics=["accuracy"])
modelCNN.fit(X_train, y_train, batch_size=batch_size, epochs=epochs, validation_split=0.2)

Epoch 1/30
375/375 [==============================] - 9s 23ms/step - loss: 0.3982 - accuracy: 0.8781 - val_loss: 0.1003 - val_accuracy: 0.9719
Epoch 2/30
375/375 [==============================] - 9s 23ms/step - loss: 0.1193 - accuracy: 0.9637 - val_loss: 0.0653 - val_accuracy: 0.9822
Epoch 3/30
375/375 [==============================] - 9s 23ms/step - loss: 0.0901 - accuracy: 0.9726 - val_loss: 0.0608 - val_accuracy: 0.9821
Epoch 4/30
375/375 [==============================] - 8s 23ms/step - loss: 0.0707 - accuracy: 0.9774 - val_loss: 0.0476 - val_accuracy: 0.9870
Epoch 5/30
375/375 [==============================] - 9s 23ms/step - loss: 0.0637 - accuracy: 0.9807 - val_loss: 0.0448 - val_accuracy: 0.9878
Epoch 6/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0576 - accuracy: 0.9823 - val_loss: 0.0445 - val_accuracy: 0.9868
Epoch 7/30
375/375 [==============================] - 8s 22ms/step - loss: 0.0528 - accuracy: 0.9835 - val_loss: 0.0410 - val_accuracy: 0.9881

##### evaluation

In [51]:
y_probab = modelCNN.predict(X_test)
y_pred = np.argmax(y_probab, axis=1)

print(classification_report(y_test, y_pred))
print(confusion_matrix(y_test, y_pred))

313/313 [==============================] - 1s 3ms/step
              precision    recall  f1-score   support

           0       0.99      1.00      0.99       980
           1       0.99      1.00      1.00      1135
           2       0.99      0.99      0.99      1032
           3       0.99      0.99      0.99      1010
           4       0.99      1.00      1.00       982
           5       0.99      0.99      0.99       892
           6       1.00      0.99      0.99       958
           7       0.99      0.99      0.99      1028
           8       0.99      0.99      0.99       974
           9       0.99      0.98      0.99      1009

    accuracy                           0.99     10000
   macro avg       0.99      0.99      0.99     10000
weighted avg       0.99      0.99      0.99     10000

[[ 978    0    0    0    0    0    0    1    1    0]
 [   0 1134    0    0    0    0    0    1    0    0]
 [   2    2 1022    0    0    0    0    5    1    0]
 [   1    0    2 1004    0 